export type Product = {
  id: string;
  brand: string;
  platform: string;
  image: string;
  name: string;
  sku: string;
  variantSize: string;
  variantColor: string;
    quantity?: number;
  status:
    | "Returned"
    | "Shipped"
    | "Picked"
    | "Packed"
    | "New"
    | "Delivered"
    | "Cancelled";
};



export const STATUS_COLORS: Record<string, string> = {
  Returned: "bg-orange-200 text-orange-800",
  Shipped: "bg-blue-200 text-blue-800",
  Picked: "bg-gray-300 text-gray-800",
  Packed: "bg-gray-200 text-gray-800",
  New: "bg-yellow-200 text-yellow-800",
  Delivered: "bg-green-200 text-green-800",
  Cancelled: "bg-red-200 text-red-800",
};


// Dummy data
export const DUMMY_DATA: Product[] = [
  {
    id: "10454646",
    brand: "Becomfy",
    platform: "Salla",
    image: "https://via.placeholder.com/40",
    name: "Premium Wireless Headphones",
    sku: "WH-001-BLK",
    variantSize: "S",
    variantColor: "White",
    status: "Returned",
    quantity: 120,
  },
  {
    id: "34567890",
    brand: "Becomfy",
    platform: "Salla",
    image: "https://via.placeholder.com/40",
    name: "Premium Wireless Headphones",
    sku: "SW-042-SLV",
    variantSize: "M",
    variantColor: "White",
    status: "Shipped",
    quantity: 80,
  },
  {
    id: "56789012",
    brand: "Becomfy",
    platform: "Salla",
    image: "https://via.placeholder.com/40",
    name: "Organic Cotton T-Shirt",
    sku: "CT-WHT-M",
    variantSize: "L",
    variantColor: "White",
    status: "Delivered",

    quantity: 200,
  },
  {
    id: "89012345",
    brand: "Becomfy",
    platform: "Salla",
    image: "https://via.placeholder.com/40",
    name: "Premium Leather Wallet",
    sku: "LW-BRN-001",
    variantSize: "XL",
    variantColor: "White",
    status: "Cancelled",
    quantity: 50,
  },
  {
    id: "10454646",
    brand: "Becomfy",
    platform: "Salla",
    image: "https://via.placeholder.com/40",
    name: "Premium Wireless Headphones",
    sku: "WH-001-BLK",
    variantSize: "S",
    variantColor: "White",
    status: "Returned",
    quantity: 120,
  },
  {
    id: "34567890",
    brand: "Becomfy",
    platform: "Salla",
    image: "https://via.placeholder.com/40",
    name: "Premium Wireless Headphones",
    sku: "SW-042-SLV",
    variantSize: "M",
    variantColor: "White",
    status: "Shipped",
    quantity: 80,
  },
  {
    id: "56789012",
    brand: "Becomfy",
    platform: "Salla",
    image: "https://via.placeholder.com/40",
    name: "Organic Cotton T-Shirt",
    sku: "CT-WHT-M",
    variantSize: "L",
    variantColor: "White",
    status: "Delivered",
    quantity: 200,
  },
  {
    id: "89012345",
    brand: "Becomfy",
    platform: "Salla",
    image: "https://via.placeholder.com/40",
    name: "Premium Leather Wallet",
    sku: "LW-BRN-001",
    variantSize: "XL",
    variantColor: "White",
    status: "Cancelled",
    quantity: 10,
  },
  {
    id: "10454646",
    brand: "Becomfy",
    platform: "Salla",
    image: "https://via.placeholder.com/40",
    name: "Premium Wireless Headphones",
    sku: "WH-001-BLK",
    variantSize: "S",
    variantColor: "White",
    status: "Returned",
    quantity:1
  },
  {
    id: "34567890",
    brand: "Becomfy",
    platform: "Salla",
    image: "https://via.placeholder.com/40",
    name: "Premium Wireless Headphones",
    sku: "SW-042-SLV",
    variantSize: "M",
    variantColor: "White",
    status: "Shipped",
    quantity:44
  },
  {
    id: "56789012",
    brand: "Becomfy",
    platform: "Salla",
    image: "https://via.placeholder.com/40",
    name: "Organic Cotton T-Shirt",
    sku: "CT-WHT-M",
    variantSize: "L",
    variantColor: "White",
    status: "Delivered",
    quantity:99
  },
  {
    id: "89012345",
    brand: "Becomfy",
    platform: "Salla",
    image: "https://via.placeholder.com/40",
    name: "Premium Leather Wallet",
    sku: "LW-BRN-001",
    variantSize: "XL",
    variantColor: "White",
    status: "Cancelled",
    quantity: 1,
  },
  {
    id: "10454646",
    brand: "Becomfy",
    platform: "Salla",
    image: "https://via.placeholder.com/40",
    name: "Premium Wireless Headphones",
    sku: "WH-001-BLK",
    variantSize: "S",
    variantColor: "White",
    status: "Returned",
    quantity:3
  },
  {
    id: "34567890",
    brand: "Becomfy",
    platform: "Salla",
    image: "https://via.placeholder.com/40",
    name: "Premium Wireless Headphones",
    sku: "SW-042-SLV",
    variantSize: "M",
    variantColor: "White",
    status: "Shipped",
    quantity:300
  },
  {
    id: "56789012",
    brand: "Becomfy",
    platform: "Salla",
    image: "https://via.placeholder.com/40",
    name: "Organic Cotton T-Shirt",
    sku: "CT-WHT-M",
    variantSize: "L",
    variantColor: "White",
    status: "Delivered",
    quantity:22
  },
  {
    id: "89012345",
    brand: "Becomfy",
    platform: "Salla",
    image: "https://via.placeholder.com/40",
    name: "Premium Leather Wallet",
    sku: "LW-BRN-001",
    variantSize: "XL",
    variantColor: "White",
    status: "Cancelled",
    quantity: 5,
  },
  {
    id: "10454646",
    brand: "Becomfy",
    platform: "Salla",
    image: "https://via.placeholder.com/40",
    name: "Premium Wireless Headphones",
    sku: "WH-001-BLK",
    variantSize: "S",
    variantColor: "White",
    status: "Returned",
    quantity: 15,
  },
  {
    id: "34567890",
    brand: "Becomfy",
    platform: "Salla",
    image: "https://via.placeholder.com/40",
    name: "Premium Wireless Headphones",
    sku: "SW-042-SLV",
    variantSize: "M",
    variantColor: "White",
    status: "Shipped",
    quantity: 60,
  },
  {
    id: "56789012",
    brand: "Becomfy",
    platform: "Salla",
    image: "https://via.placeholder.com/40",
    name: "Organic Cotton T-Shirt",
    sku: "CT-WHT-M",
    variantSize: "L",
    variantColor: "White",
    status: "Delivered",
    quantity: 150,
  },
  {
    id: "89012345",
    brand: "Becomfy",
    platform: "Salla",
    image: "https://via.placeholder.com/40",
    name: "Premium Leather Wallet",
    sku: "LW-BRN-001",
    variantSize: "XL",
    variantColor: "White",
    status: "Cancelled",
    quantity: 20,
  },
  {
    id: "10454646",
    brand: "Becomfy",
    platform: "Salla",
    image: "https://via.placeholder.com/40",
    name: "Premium Wireless Headphones",
    sku: "WH-001-BLK",
    variantSize: "S",
    variantColor: "White",
    status: "Returned",
  },
  {
    id: "34567890",
    brand: "Becomfy",
    platform: "Salla",
    image: "https://via.placeholder.com/40",
    name: "Premium Wireless Headphones",
    sku: "SW-042-SLV",
    variantSize: "M",
    variantColor: "White",
    status: "Shipped",
    quantity: 70,
  },
  {
    id: "56789012",
    brand: "Becomfy",
    platform: "Salla",
    image: "https://via.placeholder.com/40",
    name: "Organic Cotton T-Shirt",
    sku: "CT-WHT-M",
    variantSize: "L",
    variantColor: "White",
    status: "Delivered",
    quantity: 180,
  },
  {
    id: "89012345",
    brand: "Becomfy",
    platform: "Salla",
    image: "https://via.placeholder.com/40",
    name: "Premium Leather Wallet",
    sku: "LW-BRN-001",
    variantSize: "XL",
    variantColor: "White",
    status: "Cancelled",
    quantity: 25,
  },
  {
    id: "10454646",
    brand: "Becomfy",
    platform: "Salla",
    image: "https://via.placeholder.com/40",
    name: "Premium Wireless Headphones",
    sku: "WH-001-BLK",
    variantSize: "S",
    variantColor: "White",
    status: "Returned",
    quantity: 8,
  },
  {
    id: "34567890",
    brand: "Becomfy",
    platform: "Salla",
    image: "https://via.placeholder.com/40",
    name: "Premium Wireless Headphones",
    sku: "SW-042-SLV",
    variantSize: "M",
    variantColor: "White",
    status: "Shipped",
    quantity:30,
  },
  {
    id: "56789012",
    brand: "Becomfy",
    platform: "Salla",
    image: "https://via.placeholder.com/40",
    name: "Organic Cotton T-Shirt",
    sku: "CT-WHT-M",
    variantSize: "L",
    variantColor: "White",
    status: "Delivered",
    quantity: 200,
  },
  {
    id: "89012345",
    brand: "Becomfy",
    platform: "Salla",
    image: "https://via.placeholder.com/40",
    name: "Premium Leather Wallet",
    sku: "LW-BRN-001",
    variantSize: "XL",
    variantColor: "White",
    status: "Cancelled",
    quantity: 10,
  },
];
