export type Product = {
  id: string;
  brand: string;
  platform: string;
  image: string;
  name: string;
  sku: string;
  variantSize: string;
  variantColor: string;
  quantity?: number;
  status:
    | "Returned"
    | "Shipped"
    | "Picked"
    | "Packed"
    | "New"
    | "Delivered"
    | "Received"
    | "Stocked"
    | "In_Transit"
    | "Cancelled";
};

export const STATUS_COLORS: Record<string, string> = {
  Returned: "bg-orange-200 text-[#000000]",
  Shipped: "bg-[#B2EAFF] text-[#000000]",
  Picked: "bg-[#FFB697] text-[#000000]",
  Packed: "bg-[#CCCCCC] text-[#000000]",
  New: "bg-[#FFE9AE] text-[#000000]",
  Delivered: "bg-[#DCFCE7] text-[#000000]",
  Cancelled: "bg-[#FF9292] text-[#000000]",
  Received: "bg-[#CBCBCB] text-[#000000]",
  In_Transit: "bg-[#B2EAFF] text-[#000000]",
  Stocked: "bg-[#DCFCE7] text-[#000000]",
};

// Dummy data
export const DUMMY_DATA: Product[] = [
  {
    id: "10454646",
    brand: "Becomfy",
    platform: "Salla",
    image: "https://via.placeholder.com/40",
    name: "Premium Wireless Headphones",
    sku: "WH-001-BLK",
    variantSize: "S",
    variantColor: "White",
    status: "Picked",
    quantity: 120,
  },
  {
    id: "10454646",
    brand: "Becomfy",
    platform: "Salla",
    image: "https://via.placeholder.com/40",
    name: "Premium Wireless Headphones",
    sku: "WH-001-BLK",
    variantSize: "S",
    variantColor: "White",
    status: "New",
    quantity: 120,
  },
  {
    id: "9988",
    brand: "Becomfy",
    platform: "Salla",
    image: "https://via.placeholder.com/40",
    name: "Premium Wireless Headphones",
    sku: "WH-001-K",
    variantSize: "88S",
    variantColor: "White",
    status: "Packed",
    quantity: 120,
  },

  {
    id: "10454646",
    brand: "Becomfy",
    platform: "Salla",
    image: "https://via.placeholder.com/40",
    name: "Premium Wireless Headphones",
    sku: "WH-001-BLK",
    variantSize: "S",
    variantColor: "White",
    status: "Received",
    quantity: 120,
  },

  {
    id: "10454646",
    brand: "Becomfy",
    platform: "Salla",
    image: "https://via.placeholder.com/40",
    name: "Premium Wireless Headphones",
    sku: "WH-001-BLK",
    variantSize: "S",
    variantColor: "White",
    status: "Shipped",
    quantity: 120,
  },
  {
    id: "34567890",
    brand: "Becomfy",
    platform: "Salla",
    image: "https://via.placeholder.com/40",
    name: "Premium Wireless Headphones",
    sku: "SW-042-SLV",
    variantSize: "M",
    variantColor: "White",
    status: "Shipped",
    quantity: 80,
  },
  {
    id: "56789012",
    brand: "Becomfy",
    platform: "Salla",
    image: "https://via.placeholder.com/40",
    name: "Organic Cotton T-Shirt",
    sku: "CT-WHT-M",
    variantSize: "L",
    variantColor: "White",
    status: "Delivered",

    quantity: 200,
  },
  {
    id: "89012345",
    brand: "Becomfy",
    platform: "Salla",
    image: "https://via.placeholder.com/40",
    name: "Premium Leather Wallet",
    sku: "LW-BRN-001",
    variantSize: "XL",
    variantColor: "White",
    status: "Cancelled",
    quantity: 50,
  },
  {
    id: "10454646",
    brand: "Becomfy",
    platform: "Salla",
    image: "https://via.placeholder.com/40",
    name: "Premium Wireless Headphones",
    sku: "WH-001-BLK",
    variantSize: "S",
    variantColor: "White",
    status: "Returned",
    quantity: 120,
  },
  {
    id: "34567890",
    brand: "Becomfy",
    platform: "Salla",
    image: "https://via.placeholder.com/40",
    name: "Premium Wireless Headphones",
    sku: "SW-042-SLV",
    variantSize: "M",
    variantColor: "White",
    status: "Shipped",
    quantity: 80,
  },
  {
    id: "56789012",
    brand: "Becomfy",
    platform: "Salla",
    image: "https://via.placeholder.com/40",
    name: "Organic Cotton T-Shirt",
    sku: "CT-WHT-M",
    variantSize: "L",
    variantColor: "White",
    status: "Delivered",
    quantity: 200,
  },
  {
    id: "89012345",
    brand: "Becomfy",
    platform: "Salla",
    image: "https://via.placeholder.com/40",
    name: "Premium Leather Wallet",
    sku: "LW-BRN-001",
    variantSize: "XL",
    variantColor: "White",
    status: "Cancelled",
    quantity: 10,
  },
  {
    id: "10454646",
    brand: "Becomfy",
    platform: "Salla",
    image: "https://via.placeholder.com/40",
    name: "Premium Wireless Headphones",
    sku: "WH-001-BLK",
    variantSize: "S",
    variantColor: "White",
    status: "Returned",
    quantity: 1,
  },
  {
    id: "34567890",
    brand: "Becomfy",
    platform: "Salla",
    image: "https://via.placeholder.com/40",
    name: "Premium Wireless Headphones",
    sku: "SW-042-SLV",
    variantSize: "M",
    variantColor: "White",
    status: "Shipped",
    quantity: 44,
  },
  {
    id: "56789012",
    brand: "Becomfy",
    platform: "Salla",
    image: "https://via.placeholder.com/40",
    name: "Organic Cotton T-Shirt",
    sku: "CT-WHT-M",
    variantSize: "L",
    variantColor: "White",
    status: "Delivered",
    quantity: 99,
  },
  {
    id: "89012345",
    brand: "Becomfy",
    platform: "Salla",
    image: "https://via.placeholder.com/40",
    name: "Premium Leather Wallet",
    sku: "LW-BRN-001",
    variantSize: "XL",
    variantColor: "White",
    status: "Cancelled",
    quantity: 1,
  },
  {
    id: "10454646",
    brand: "Becomfy",
    platform: "Salla",
    image: "https://via.placeholder.com/40",
    name: "Premium Wireless Headphones",
    sku: "WH-001-BLK",
    variantSize: "S",
    variantColor: "White",
    status: "Returned",
    quantity: 3,
  },
  {
    id: "34567890",
    brand: "Becomfy",
    platform: "Salla",
    image: "https://via.placeholder.com/40",
    name: "Premium Wireless Headphones",
    sku: "SW-042-SLV",
    variantSize: "M",
    variantColor: "White",
    status: "Shipped",
    quantity: 300,
  },
  {
    id: "56789012",
    brand: "Becomfy",
    platform: "Salla",
    image: "https://via.placeholder.com/40",
    name: "Organic Cotton T-Shirt",
    sku: "CT-WHT-M",
    variantSize: "L",
    variantColor: "White",
    status: "Delivered",
    quantity: 22,
  },
  {
    id: "89012345",
    brand: "Becomfy",
    platform: "Salla",
    image: "https://via.placeholder.com/40",
    name: "Premium Leather Wallet",
    sku: "LW-BRN-001",
    variantSize: "XL",
    variantColor: "White",
    status: "Cancelled",
    quantity: 5,
  },
  {
    id: "10454646",
    brand: "Becomfy",
    platform: "Salla",
    image: "https://via.placeholder.com/40",
    name: "Premium Wireless Headphones",
    sku: "WH-001-BLK",
    variantSize: "S",
    variantColor: "White",
    status: "Returned",
    quantity: 15,
  },
  {
    id: "34567890",
    brand: "Becomfy",
    platform: "Salla",
    image: "https://via.placeholder.com/40",
    name: "Premium Wireless Headphones",
    sku: "SW-042-SLV",
    variantSize: "M",
    variantColor: "White",
    status: "Shipped",
    quantity: 60,
  },
  {
    id: "56789012",
    brand: "Becomfy",
    platform: "Salla",
    image: "https://via.placeholder.com/40",
    name: "Organic Cotton T-Shirt",
    sku: "CT-WHT-M",
    variantSize: "L",
    variantColor: "White",
    status: "Delivered",
    quantity: 150,
  },
  {
    id: "89012345",
    brand: "Becomfy",
    platform: "Salla",
    image: "https://via.placeholder.com/40",
    name: "Premium Leather Wallet",
    sku: "LW-BRN-001",
    variantSize: "XL",
    variantColor: "White",
    status: "Cancelled",
    quantity: 20,
  },
  {
    id: "10454646",
    brand: "Becomfy",
    platform: "Salla",
    image: "https://via.placeholder.com/40",
    name: "Premium Wireless Headphones",
    sku: "WH-001-BLK",
    variantSize: "S",
    variantColor: "White",
    status: "Returned",
  },
  {
    id: "34567890",
    brand: "Becomfy",
    platform: "Salla",
    image: "https://via.placeholder.com/40",
    name: "Premium Wireless Headphones",
    sku: "SW-042-SLV",
    variantSize: "M",
    variantColor: "White",
    status: "Shipped",
    quantity: 70,
  },
  {
    id: "56789012",
    brand: "Becomfy",
    platform: "Salla",
    image: "https://via.placeholder.com/40",
    name: "Organic Cotton T-Shirt",
    sku: "CT-WHT-M",
    variantSize: "L",
    variantColor: "White",
    status: "Delivered",
    quantity: 180,
  },
  {
    id: "89012345",
    brand: "Becomfy",
    platform: "Salla",
    image: "https://via.placeholder.com/40",
    name: "Premium Leather Wallet",
    sku: "LW-BRN-001",
    variantSize: "XL",
    variantColor: "White",
    status: "Cancelled",
    quantity: 25,
  },
  {
    id: "10454646",
    brand: "Becomfy",
    platform: "Salla",
    image: "https://via.placeholder.com/40",
    name: "Premium Wireless Headphones",
    sku: "WH-001-BLK",
    variantSize: "S",
    variantColor: "White",
    status: "Returned",
    quantity: 8,
  },
  {
    id: "34567890",
    brand: "Becomfy",
    platform: "Salla",
    image: "https://via.placeholder.com/40",
    name: "Premium Wireless Headphones",
    sku: "SW-042-SLV",
    variantSize: "M",
    variantColor: "White",
    status: "Shipped",
    quantity: 30,
  },
  {
    id: "56789012",
    brand: "Becomfy",
    platform: "Salla",
    image: "https://via.placeholder.com/40",
    name: "Organic Cotton T-Shirt",
    sku: "CT-WHT-M",
    variantSize: "L",
    variantColor: "White",
    status: "Delivered",
    quantity: 200,
  },
  {
    id: "89012345",
    brand: "Becomfy",
    platform: "Salla",
    image: "https://via.placeholder.com/40",
    name: "Premium Leather Wallet",
    sku: "LW-BRN-001",
    variantSize: "XL",
    variantColor: "White",
    status: "Cancelled",
    quantity: 10,
  },
];
